name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: actions/checkout@v3

      

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build Docker Image
        run: |
          docker build --no-cache -t selenium_with_bdd .
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

      - name: Run Test
        run: docker run -t selenium_with_bdd
