name: Python Selenium

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r req.txt


      - name: Set up EdgeDriver
        run: |
          EDGEDRIVER_VERSION=$(curl -sS https://msedgedriver.azureedge.net/LATEST_STABLE)
          wget https://msedgedriver.azureedge.net/$EDGEDRIVER_VERSION/edgedriver_linux64.zip
          unzip edgedriver_linux64.zip
          chmod +x msedgedriver
          sudo mv msedgedriver /usr/local/bin/
          
      - name: Run Behave Tests
        run: |
          behave

